<script setup>
import { useNoise } from '#/use/noise.js'
const {
  options, filterOptions, pannerOptions, crusherOptions, active, fftData, fftFreq, types, filterTypes, filterLFOTypes
} = useNoise();
</script>


<template lang="pug">
.row.is-group.gap-2
  control-push(v-model="active" title="NOISE")
  control-rotary(
    :min="0"
    :max="1"
    v-model="options.volume"
    :step="0.01"
    param="DRY"
  )
  control-choose(
    v-model="options.noise.type"
    :variants="types"
  )
  .is-group.flex.flex-wrap.p-1
    control-rotary(
      :min="0.005"
      :max="4"
      :step="0.01"
      param="ATT"
      v-model="options.envelope.attack"
    )
    control-rotary(
      :min="0.005"
      :max="6"
      :step="0.01"
      param="DEC"
      v-model="options.envelope.decay"
    )
    control-rotary(
      :min="0.005"
      :max="1"
      :step="0.01"
      param="SUS"
      v-model="options.envelope.sustain"
    )
    control-rotary(
      :min="0.005"
      :max="10"
      :step="0.01"
      param="REL"
      v-model="options.envelope.release"
    )
  svg.w-8rem.border-1.rounded-lg.m-1(
    version="1.1",
    baseProfile="full",
    viewBox="0 0 32 10",
    xmlns="http://www.w3.org/2000/svg",
  )
    line(
      v-for="(fr, i) in fftFreq"
      :key="fr"
      stroke-width="1"
      stroke="gray"
      :x1="i"
      :x2="i"
      :y2="10"
      :y1="10 - fftData[i] * 50"
      :title="fftFreq[i]"
    )
.row.is-group.gap-2
  .flex.flex-wrap.gap-2
    control-push(
      title="FILTER"
      v-model="filterOptions.on"
    )
    control-rotary(
      param="VOL"
      :min="0"
      :max="1"
      :step="0.01"
      :fixed="1"
      v-model="filterOptions.volume"
    )
    control-rotary(
      param="FREQ"
      :min="10"
      :max="999"
      :step="1"
      :fixed="0"
      unit="hz"
      v-model="filterOptions.baseFrequency"
    )
    control-rotary(
      param="OCT"
      :min="0.1"
      :max="7"
      :step="0.1"
      :fixed="1"
      v-model="filterOptions.octaves"
    )
    control-rotary(
      param="Q"
      :min="0.1"
      :max="20"
      :step="0.1"
      :fixed="1"
      v-model="filterOptions.filter.Q"
    )
    control-rotary(
      param="WET"
      :min="0"
      :max="1"
      :step="0.1"
      :fixed="1"
      unit=""
      v-model="filterOptions.wet"
    )
    control-choose(
      v-model="filterOptions.filter.type"
      :variants="filterTypes"
    ) 
  .flex.flex-wrap.gap-2
    control-push(
      title="PLAY"
      v-model="filterOptions.play"
    )
    control-rotary(
      param="LFO"
      :min="0.01"
      :max="4"
      :step="0.01"
      :fixed="2"
      unit="hz"
      v-model="filterOptions.frequency"
    )
    control-rotary(
      param="DPTH"
      :min="0"
      :max="1"
      :step="0.1"
      :fixed="1"
      unit=""
      v-model="filterOptions.depth"
    )
    control-choose(
      v-model="filterOptions.type"
      :variants="filterLFOTypes"
    )
.row.is-group.gap-2
  control-push(
    title="BITCRUSHER"
    v-model="crusherOptions.on"
    )

  control-rotary(
    param="VOL"
    :min="0.01"
    :max="1"
    :step="0.01"
    :fixed="1"
    v-model="crusherOptions.volume"
  )
  control-rotary(
    param="BITS"
    :min="1"
    :max="16"
    :step="0.01"
    :fixed="2"
    v-model="crusherOptions.bits"
  )
  control-rotary(
    param="WET"
    :min="0"
    :max="1"
    :step="0.1"
    :fixed="1"
    unit=""
    v-model="crusherOptions.wet"
  )
.row.is-group.gap-2
  control-push(
    title="PAN"
    v-model="pannerOptions.on"
    )
  control-push(
    title="PLAY"
    v-model="pannerOptions.play"
    )
  control-rotary(
    param="VOL"
    :min="0.01"
    :max="1"
    :step="0.01"
    :fixed="1"
    v-model="pannerOptions.volume"
  )
  control-rotary(
    param="LFO"
    :min="0.01"
    :max="4"
    :step="0.01"
    :fixed="2"
    unit="hz"
    v-model="pannerOptions.frequency"
  )
  control-rotary(
    param="DPTH"
    :min="0"
    :max="1"
    :step="0.1"
    :fixed="1"
    unit=""
    v-model="pannerOptions.depth"
  )
  control-rotary(
    param="WET"
    :min="0"
    :max="1"
    :step="0.1"
    :fixed="1"
    unit=""
    v-model="pannerOptions.wet"
  )


</template>

<style lang="postcss" scoped>
.row {
  @apply w-full my-2 flex justify-start flex-wrap border-1 p-2 rounded-lg max-w-65ch mx-auto;
}
</style>